version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  deploy:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies
      - run:
          command: |
            yarn install --prefer-offline
      - save_cache:
          paths:
            - node_modules/
          key: dependencies-{{ checksum "yarn.lock" }}
      - run:
          command: yarn build
      - aws-s3/sync:
          aws-region: 'us-east-1'
          from: build
          to: 's3://sonar.circulo.dev'

workflows:
  version: 2
  ci:
    jobs:
      - deploy
